require('dotenv').config()

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_LAYANAN = 'pojok-shoes/layanan'
const CLOUDINARY_PROFILE = 'pojok-shoes/profile'

module.exports = {
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_LAYANAN,
    CLOUDINARY_PROFILE
}